services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo:16.1.0
    container_name: piwigo
    environment:
      - PUID=103
      - PGID=996
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - freezer_vault:/gallery:ro
    devices:
      - /dev/dri:/dev/dri
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.piwigo.loadBalancer.server.port=80"
      - "traefik.http.routers.piwigo-local.entrypoints=http,https"
      - "traefik.http.routers.piwigo-local.rule=Host(`piwigo.fridge.local`)"

volumes:
  config:
  freezer_vault:
    external: true

networks:
  traefik:
    name: traefik
    external: true
